// This file is autogenerated by Lingo from your localized strings file.

import Foundation

private class BundleLocator {
    static let bundle: Bundle = Bundle(for: BundleLocator.self)
}

struct Lingo {
    struct Test {
        /// "TestFrameworkTests"
        static let title = NSLocalizedString("Test.title", bundle: BundleLocator.bundle, comment: "")
    }
}
