// This file was generated by the `VersionFile` package plugin.

/// Namespace for the current version of the target in which this file is contained.
enum Version {
    /// The current version number.
    static let number = "1.1.3"
}