name: Test

on:
  workflow_call:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yml'
      - '**.swift'
      - 'Package.resolved'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - '.github/workflows/test.yml'
      - '**.swift'
      - 'Package.resolved'

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    if: github.event.pull_request.draft == false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', 'Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build
      run: swift build -v

    - name: Run tests
      # Need to use `--parallel` to generate the report: https://github.com/apple/swift-package-manager/issues/4752
      run: swift test --xunit-output report.xml --parallel --num-workers=1

    - name: Report
      if: success() || failure()
      uses: dorny/test-reporter@v1
      with:
        name: Report Results
        path: report.xml
        reporter: java-junit
